### PR TITLE
Start making builder

### PR DESCRIPTION
**Pull request by Yustynn**
Added global event emitter for communication between game, levelCreator and angular
Removed game from index.html, added it to home page only.
Basic setup for levelCreator

### CODE REVIEW

**Comment by LanaCoyote** [comment]
Looking good. Have you confirmed that you can connect to the event emitter?

**Comment by everett980** [comment]
click = great success

**Comment by Yustynn** [comment]
Yup, event emitter works

**Comment by LanaCoyote** [comment]
Sounds good. Merge when ready, in case you have more to push up

**Pull request merged**
